version: '3'

services:

  app:
    image: renedanni/node:fullcy
    container_name: app
    networks: 
      - node-network
    tty: true
    entrypoint: ["node", "index.js"]
    depends_on:
      - db

  
  db:
    image: renedanni/mysql:fullcy
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks: 
      - node-network


  nginx:
    image: renedanni/nginx:fullcy
    container_name: nginx
    restart: always
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - app

networks:
  node-network:
    driver: bridge
